PROGS    = gallery
PKGS     = glib-2.0
CLEAN    = html.c
CPPFLAGS = -I..
CFLAGS   = --std=c99 -Wall -Wno-format -g

default:V: gallery
	QUERY_STRING=foo ./gallery

gallery: gallery.o html.o ../lib.o

<../mkcommon
